version: "3.0"
services:
  mysql:
    image: mysql:8.0.26
    privileged: true
    container_name: adminApi_mysql
    ports:
      - "3306:3306"
    volumes:
      - "./mysql/data:/var/lib/mysql"
      # - "./mysql/conf.d:/etc/mysql/conf.d"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - "MYSQL_ROOT_PASSWORD=ljzyou2513"
      - "TZ=Asia/Shanghai"
      - "SET_CONTAINER_TIMEZONE=true"
      - "CONTAINER_TIMEZONE=Asia/Shanghai"
    restart: always

  redis:
    image: redis:6.2.6
    privileged: true
    container_name: adminApi_redis
    ports:
      - "6379:6379"
    volumes:
      - "./redis/data:/data:rw"
      - "./redis/redis.conf:/usr/local/etc/redis/redis.conf:rw"
    environment:
      - "TZ=Asia/Shanghai"
      - "LANG=en_US.UTF-8"
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass "ljzyou2513"

  nginx:
    image: nginx:1.18.0
    container_name: adminApi_nginx
    ports:
      - "80:80"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:rw"
      - "./nginx/html:/usr/share/nginx/html/"
    restart: always

  rabbitmq:
    image: rabbitmq:3.8.30
    container_name: adminApi_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "./rabbitmq/data:/var/lib/rabbitmq/"
    restart: always

  portainer:
    image: portainer/portainer:latest
    container_name: adminApi_portainer
    ports:
      - "9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    privileged: true
    restart: always

  java:
    container_name: adminApi_java
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - mysql
      - redis
      - nginx
      - portainer
      - rabbitmq